const images = {
  logo: require('../assets/images/Logo.png'),
  google: require('../assets/images/google.png'),
  apple: require('../assets/images/apple.png'),
  passwordShow: require('../assets/images/passwordShow.png'),
  passwordhide: require('../assets/images/passwordhide.png'),
  downArrow: require('../assets/images/downArrow.png'),
  backImage: require('../assets/images/backImage.png'),
  home: require('../assets/images/home.png'),
  calender: require('../assets/images/calender.png'),
  checkIn: require('../assets/images/checkIn.png'),
  alerts: require('../assets/images/alerts.png'),
  menu: require('../assets/images/menu.png'),
  search: require('../assets/images/search.png'),
  user: require('../assets/images/user.png'),
  admin: require('../assets/images/admin.jpg'),
  kitchenA: require('../assets/images/kitchenA.png'),
  Kitchencard: require('../assets/images/kitchencard.png'),
  mapIcon: require('../assets/images/mapIcon.png'),
  thankYou: require('../assets/images/thankYou.png'),
  clock: require('../assets/images/clock.png'),
  chat: require('../assets/images/chat.png'),
  upload: require('../assets/images/upload.png'),
  masterCard: require('../assets/images/masterCard.png'),
  // hemberger: require('../assets/images/hemberger.png'),
  notification: require('../assets/images/notification.png'),
  // background: require('../assets/images/background.jpeg'),
  // camera: require('../assets/images/camera.png'),
  // bulb: require('../assets/images/bulb.png'),
  // case: require('../assets/images/case.png'),
  // closet: require('../assets/images/closet.png'),
  // calendar: require('../assets/images/calendar.png'),
  // heart: require('../assets/images/heart.png'),
  // share: require('../assets/images/share.png'),
  // charity: require('../assets/images/charity.png'),
  // homeDiv: require('../assets/images/homeDiv.png'),
  // modalCamera: require('../assets/images/modalCamera.png'),
  // gallery: require('../assets/images/gallery.png'),
  // suit: require('../assets/images/suit.png'),
  // suit2: require('../assets/images/suit2.png'),
  // suit3: require('../assets/images/suit3.png'),
  // suit4: require('../assets/images/suit4.png'),
  // suit5: require('../assets/images/suit5.png'),
  // suit6: require('../assets/images/suit6.png'),
  // suit7: require('../assets/images/suit7.png'),
  // suit8: require('../assets/images/suit8.png'),
  // suit9: require('../assets/images/suit9.png'),
  // suit10: require('../assets/images/suit10.png'),
  // suit11: require('../assets/images/suit11.png'),
  // suit12: require('../assets/images/suit12.png'),
  // suit13: require('../assets/images/suit13.png'),
  // suit14: require('../assets/images/suit14.png'),
  // tick: require('../assets/images/tick.png'),
  // plus: require('../assets/images/plus.png'),
  // delete: require('../assets/images/delete.png'),
  // search: require('../assets/images/search.png'),
  // mage_filter: require('../assets/images/mage_filter.png'),
  // editIcon: require('../assets/images/editIcon.png'),
  // closetSuit: require('../assets/images/closetSuit.png'),
  // closetSuit1: require('../assets/images/closetSuit1.png'),
  // closetSuit2: require('../assets/images/closetSuit2.png'),
  // closetSuit3: require('../assets/images/closetSui3.png'),
  // closetSuit4: require('../assets/images/closetSuit4.png'),

  // shoes: require('../assets/images/shoes.png'),
  // formal: require('../assets/images/formal.png'),
  // glasses: require('../assets/images/glasses.png'),
  // jacket: require('../assets/images/jacket.png'),
  // cloth: require('../assets/images/cloth.png'),
  // watch: require('../assets/images/watch.png'),
  // shirt: require('../assets/images/shirt.png'),
  // whiteShoes: require('../assets/images/whiteShoes.png'),
  // Calendar2: require('../assets/images/Calendar2.png'),
  // heart1: require('../assets/images/heart1.png'),
  // download: require('../assets/images/download.png'),

  // copyLink: require('../assets/images/copyLink.png'),
  // skype: require('../assets/images/skype.png'),
  // instagram: require('../assets/images/instagram.png'),
  // messanger: require('../assets/images/messanger.png'),
  // messages: require('../assets/images/messages.png'),
  // watsapp: require('../assets/images/watsapp.png'),
  // x: require('../assets/images/x.png'),
  // socialFacebook: require('../assets/images/socialFacebook.png'),
  // send: require('../assets/images/send.png'),
  // voice: require('../assets/images/voice.png'),
  // gallerySend: require('../assets/images/gallerySend.png'),

  // homeIcon: require('../assets/images/homeIcon.png'),
  // userIcon: require('../assets/images/UserIcon.png'),
  // lockIcon: require('../assets/images/lockIcon.png'),
  // familyIcon: require('../assets/images/familyIcon.png'),
  // documentIcon: require('../assets/images/documentIcon.png'),
  // privacyPolicyIcon: require('../assets/images/privacyPolicyIcon.png'),
  // cross: require('../assets/images/cross.png'),
  // logout: require('../assets/images/logout.png'),
  // camera2: require('../assets/images/camerawhite.png'),
  // Congrats:require('../assets/images/circleCheck.png'),
  // Ellipse:require('../assets/images/Ellipse.png'),
  // brother:require('../assets/images/brother.png'),
  // sister:require('../assets/images/sister.png'),
  // husband:require('../assets/images/husband.png'),
};

export default images;
