const images = {
  logo: require('../assets/images/Logo.png'),
  google: require('../assets/images/google.png'),
  apple: require('../assets/images/apple.png'),
  passwordShow: require('../assets/images/passwordShow.png'),
  passwordhide: require('../assets/images/passwordhide.png'),
  downArrow: require('../assets/images/downArrow.png'),
  backImage: require('../assets/images/backImage.png'),
  home: require('../assets/images/home.png'),
  calender: require('../assets/images/calender.png'),
  checkIn: require('../assets/images/checkIn.png'),
  alerts: require('../assets/images/alerts.png'),
  menu: require('../assets/images/menu.png'),
  search: require('../assets/images/search.png'),
  user: require('../assets/images/user.png'),
  admin: require('../assets/images/user.png'),
  kitchenA: require('../assets/images/kitchenA.png'),
  Kitchencard: require('../assets/images/kitchencard.png'),
  mapIcon: require('../assets/images/mapIcon.png'),
  thankYou: require('../assets/images/thankYou.png'),
  clock: require('../assets/images/clock1.png'),
  chat: require('../assets/images/chat.png'),
  upload: require('../assets/images/upload.png'),
  masterCard: require('../assets/images/masterCard.png'),
  password: require('../assets/images/password.png'),
  support: require('../assets/images/support.png'),
  delete: require('../assets/images/delete.png'),
  camera: require('../assets/images/camera.png'),
  bookings: require('../assets/images/bookings.png'),
  documents: require('../assets/images/documents.png'),
  arrow: require('../assets/images/arrow.png'),
  terms: require('../assets/images/terms.png'),
  payments: require('../assets/images/payments.png'),
  personal: require('../assets/images/personal.png'),
  bell: require('../assets/images/bell.png'),
  notification: require('../assets/images/notification.png'),
};

export default images;
